Fashion/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fashion.Models;

namespace Fashion.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BrandsController : Controller
    {
        private ProductDbContext db = new ProductDbContext();

        // GET: Brands
        public ActionResult Index()
        {
            return View(db.Brands.ToList());
        }

        // GET: Brands/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // GET: Brands/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Brands/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Brands.Add(brand);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(brand);
        }

        // GET: Brands/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: Brands/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                db.Entry(brand).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(brand);
        }

        // GET: Brands/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Brand brand = db.Brands.Find(id);
            if (brand == null)
            {
                return HttpNotFound();
            }
            return View(brand);
        }

        // POST: Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Brand brand = db.Brands.Find(id);
            db.Brands.Remove(brand);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Fashion/Controllers/HomeController.cs
using Fashion.Models;
using Fashion.ViewModels;
using System.Web.Mvc;
using System.Data.Entity;
using System.Linq;
using System.Collections.Generic;
using System;

namespace Fashion.Controllers
{
    public class HomeController : Controller
    {
        private ProductDbContext _db = new ProductDbContext();

        [ChildActionOnly]
        public ActionResult Category()
        {
            return View(_db.Categories.ToList());
        }

        [ChildActionOnly]
        public ActionResult Brand()
        {
           return View(_db.Brands.ToList());
        }

        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


        public JsonResult GetProduct(Guid id)
        {
           // --- Truy vấn đến sản phẩm trùng id
            var sp = _db.Products
                        .Where(p => p.ID.Equals(id))
                        .Select(p=> new ProductDetail()
                        {
                            // --- Chỉ lấy tên 
                            Brand = p.Brand.Name,
                            Category = p.Category.Name,
                            // --- Trả về mảng các string cắt nhau bởi khoảng trắng
                            Colors = p.Color,
                            // --- Chỉ select link của mỗi Image
                            Images = p.Images.Select(x => x.Link).ToList(),
                            Info = p.Info,
                            Cost = p.Cost,
                            ID = p.ID,
                            Sizes = p.Size,
                            InStock = p.Instock,
                            Name = p.Name
                        });
            if (sp == null)
                return null;
            return Json(sp ,JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetProducts()
        {
            // --- Khởi tạo danh sách chứa sản phẩm
            // --- Lấy 9 sản phẩm và thêm vào list
            var temp = _db.Products.Take(9).Select(p => new ProductVm()
            {
                Name = p.Name,
                Category = p.Category.Name,
                Cost = p.Cost,
                ID = p.ID,
                Brand = p.Brand.Name,
                Image = p.Images.FirstOrDefault().Link
            });

            if (temp == null)
                return null;

            // --- Trả về danh sách dưới dạng JSON
            return Json(temp, JsonRequestBehavior.AllowGet);
        }
    }
}

Fashion/Views/Shared/_Cart.cshtml
<li class="m_left_5 relative container3d" id="shopping_button">
    <a role="button" href="#" class="button_type_3 color_light bg_scheme_color d_block r_corners tr_delay_hover box_s_none">
        <span class="d_inline_middle shop_icon m_mxs_right_0">
            <i class="fa fa-shopping-cart"></i>
            <span class="count tr_delay_hover type_2 circle t_align_c">{{vm.carts.count}}</span>
        </span>
        <b class="d_mxs_none">Tổng cộng : {{vm.carts.total}}</b>
    </a>
    <div class="shopping_cart top_arrow tr_all_hover r_corners">
        <div class="f_size_medium sc_header">Giỏ hàng của bạn</div>
        <ul class="products_list">
            <li ng-repeat="item in vm.carts.items">
                <div class="clearfix">
                    <!--product image-->
                    <img class="f_left m_right_10" src="~/{{item.Image}}" alt="">
                    <!--product description-->
                    <div class="f_left product_description">
                        <a href="#" class="color_dark m_bottom_5 d_block">{{item.Name}}</a>
                        <a href="#" class="color_dark m_bottom_5 d_block">Danh Mục: {{item.Category}}</a>
                        <a href="#" class="color_dark m_bottom_5 d_block">Thương Hiệu: {{item.Brand}} </a>
 
                    </div>
                    <!--product price-->
                    <div class="f_left f_size_medium">
                        <div class="clearfix">
                            {{vm.carts.num[$index]}} x <b class="color_dark">{{item.Cost | number : c0}} VNĐ</b>
                        </div>
                        <button ng-click="vm.remove(item)" class="close_product color_dark tr_hover"><i class="fa fa-times"></i></button>
                    </div>
                </div>
            </li>

        </ul>
        <!--total price-->
        <ul class="total_price bg_light_color_1 t_align_r color_dark">
            <li>Số Sản Phẩm : <b class="f_size_large bold scheme_color sc_price t_align_l d_inline_b m_left_15"> {{vm.carts.count}}</b></li>
            <li>Tổng cộng : <b class="f_size_large bold scheme_color sc_price t_align_l d_inline_b m_left_15"> {{vm.carts.total}}</b></li>
        </ul>
        <div class="sc_footer t_align_c">
            <a ng-click="vm.clear()" role="button" class="button_type_4 d_inline_middle bg_light_color_2 r_corners color_dark t_align_c tr_all_hover m_mxs_bottom_5">Làm Trống Giỏ</a>
            <a href="#" role="button" class="button_type_4 bg_scheme_color d_inline_middle r_corners tr_all_hover color_light">Thanh Toán</a>
        </div>
    </div>
</li>

Fashion/Views/Shared/_Header.cshtml
@using Microsoft.AspNet.Identity


<section class="h_top_part">
    <div class="container">
        <div class="row clearfix">
            <div class="col-lg-4 col-md-4 col-sm-5 t_xs_align_c">
                
                @if (Request.IsAuthenticated)
                {
                    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        @Html.AntiForgeryToken()
                        <p class="f_size_small"> @Html.ActionLink("Tài khoản : " + User.Identity.GetUserName() + " ---- ", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" }) <a href="javascript:document.getElementById('logoutForm').submit()">Thoát Tài Khoản</a> </p>

                    }
                }
                else
                {
                    <p class="f_size_small">Chào mừng khách hàng mới : Vui lòng 	<a href="#" data-popup="#login_popup">Đăng Nhập</a> hoặc  @Html.ActionLink("Đăng Ký", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" }) </p>

                }

            </div>
            <div class="col-lg-4 col-md-4 col-sm-2 t_align_c t_xs_align_c">
                <p class="f_size_small">Đường dây nóng : <b class="color_dark">0977 966 549</b></p>
            </div>
            <nav class="col-lg-4 col-md-4 col-sm-5 t_align_r t_xs_align_c">
                <ul class="d_inline_b horizontal_list clearfix f_size_small users_nav">
                    <li><a href="#" class="default_t_color">Danh Sách Yêu Thích </a></li>
                    <li><a href="#" class="default_t_color">Thanh Toán </a></li>
                </ul>
            </nav>
        </div>
    </div>
</section>

Fashion/Views/Shared/_Home.cshtml
<!doctype html>
 
<html lang="en" ng-app="Store" ng-controller="HomeCtrl as vm">
<!--<![endif]-->
<head>
    <title>AGK FASHION - Thời Trang Trẻ</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <!--meta info-->
    <meta name="author" content="">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <link rel="icon" type="image/ico" href="~/Content/images/fav.ico">

       @Styles.Render("~/css")
    
</head>
    <body>
        <div class="boxed_layout relative w_xs_auto">
            <header role="banner">
                @Html.Partial("~/Views/Shared/_Header.cshtml")
                <section class="h_bot_part container">
                    <div class="clearfix row">
                        <div class="col-lg-6 col-md-6 col-sm-4 t_xs_align_c">
                            <a href="~/" class="logo m_xs_bottom_15 d_xs_inline_b">
                                <img src="~/Content/images/logo.png" alt="">
                            </a>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-8 t_align_r t_xs_align_c">
                            <ul class="d_inline_b horizontal_list clearfix t_align_l site_settings">
                                
                                @Html.Partial("/Views/Shared/_Cart.cshtml")
                            </ul>
                        </div>
                    </div>
                </section>
                <section class="menu_wrap relative">
                    <div class="container clearfix">
                        <button id="menu_button" class="r_corners centered_db d_none tr_all_hover d_xs_block m_bottom_10">
                            <span class="centered_db r_corners"></span>
                            <span class="centered_db r_corners"></span>
                            <span class="centered_db r_corners"></span>
                        </button>
                        <nav role="navigation" class="f_left f_xs_none d_xs_none">
                            <ul class="horizontal_list main_menu clearfix">
                                <li class="relative f_xs_none m_xs_bottom_5"><a href="~/" class="tr_delay_hover color_light tt_uppercase"><b>Trang Chủ</b></a></li>
                                <li class="relative f_xs_none m_xs_bottom_5">
                                    <a href="~/SanPham/DanhMuc/1" class="tr_delay_hover color_light tt_uppercase"><b>Danh Mục Sản Phẩm</b></a>
                                    @Html.Action("Category", "Home")
                                   
                                </li>
                                <li class="relative f_xs_none m_xs_bottom_5">
                                    <a href="~/SanPham/DanhMuc/1" class="tr_delay_hover color_light tt_uppercase"><b>Thương Hiệu Nổi Tiếng</b></a>
                                    @Html.Action("Brand", "Home")
                                </li>
                                <li class="relative f_xs_none m_xs_bottom_5"><a href="contact.html" class="tr_delay_hover color_light tt_uppercase"><b>Liên Hệ</b></a></li>

                         </ul>
                        </nav>
                        <button class="f_right search_button tr_all_hover f_xs_none d_xs_none btn-d">
                            <b> Tìm Kiếm </b>
                        </button>
                    </div>
                    <div class="searchform_wrap tf_xs_none tr_all_hover">
                        <div class="container vc_child h_inherit relative">
                            <form role="search" class="d_inline_middle full_width">
                                <input type="text" ng-model="$key" name="search" placeholder="Nhập từ khóa để tìm kiếm..." class="f_size_large">
                            </form>
                            <button class="close_search_form tr_all_hover d_xs_none color_dark">
                                <i class="fa fa-times"></i>
                            </button>
                        </div>
                    </div>
                </section>
            </header>
           
            <div class="page_content_offset">
                @RenderBody()
           
            </div>
            <div class="row clearfix">
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <a href="#" class="d_block animate_ftb h_md_auto m_xs_bottom_15 banner_type_2 r_corners red t_align_c tt_uppercase vc_child n_sm_vc_child">
                        <span class="d_inline_middle">
                            <img class="d_inline_middle m_md_bottom_5" src="~/Content/images/banner_img_3.png" alt="">
                            <span class="d_inline_middle m_left_10 t_align_l d_md_block t_md_align_c">
                                <b>Đảm bảo 100%</b><br><span class="color_dark">Chất Lượng</span>
                            </span>
                        </span>
                    </a>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <a href="#" class="d_block animate_ftb h_md_auto m_xs_bottom_15 banner_type_2 r_corners green t_align_c tt_uppercase vc_child n_sm_vc_child">
                        <span class="d_inline_middle">
                            <img class="d_inline_middle m_md_bottom_5" src="~/Content/images/banner_img_4.png" alt="">
                            <span class="d_inline_middle m_left_10 t_align_l d_md_block t_md_align_c">
                                <b>Miễn Phí Chuyển Hàng</b><br><span class="color_dark">Mọi Sản Phẩm</span>
                            </span>
                        </span>
                    </a>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4">
                    <a href="#" class="d_block animate_ftb h_md_auto banner_type_2 r_corners orange t_align_c tt_uppercase vc_child n_sm_vc_child">
                        <span class="d_inline_middle">
                            <img class="d_inline_middle m_md_bottom_5" src="~/Content/images/banner_img_5.png" alt="">
                            <span class="d_inline_middle m_left_10 t_align_l d_md_block t_md_align_c">
                                <b>Tri Ân Khách Hàng</b><br><span class="color_dark">Giảm 10% </span>
                            </span>
                        </span>
                    </a>
                </div>
            </div>
            <p></p>
            <footer id="footer">
                <div class="footer_bottom_part">
                    <div class="container clearfix t_mxs_align_c">
                        <p class="f_left f_mxs_none m_mxs_bottom_10">&copy; 2014 <span class="color_light">AGK GROUP</span>. All Rights Reserved.</p>
                        <ul class="f_right horizontal_list clearfix f_mxs_none d_mxs_inline_b">
                            <li><img src="~/Content/images/payment_img_1.png" alt=""></li>
                            <li class="m_left_5"><img src="~/Content/images/payment_img_2.png" alt=""></li>
                            <li class="m_left_5"><img src="~/Content/images/payment_img_3.png" alt=""></li>
                            <li class="m_left_5"><img src="~/Content/images/payment_img_4.png" alt=""></li>
                            <li class="m_left_5"><img src="~/Content/images/payment_img_5.png" alt=""></li>
                        </ul>
                    </div>
                </div>
            </footer>
        </div>
        
        

        @Html.Partial("/Views/Shared/_Login.cshtml")
        @Html.Partial("/Views/Shared/_PopupView.cshtml")
        
        <button class="t_align_c r_corners tr_all_hover animate_ftl" id="go_to_top"><i class="fa fa-angle-up"></i></button>
        @Scripts.Render("/js")
        @Scripts.Render("~/app")


    </body>
</html>

Fashion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AGK FASHION</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AGK FASHION", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Manage")</li>
                    <li>@Html.ActionLink("Cá Nhân", "Index", "Customers")</li>
                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Users", "Index", "UsersAdmin")</li>
                        <li>@Html.ActionLink("Sản Phẩm", "Index", "Products")</li>
                        <li>@Html.ActionLink("Danh Mục", "Index", "Categories")</li>
                        <li>@Html.ActionLink("Thương Hiệu", "Index", "Brands")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Nhật Khoa - Thúy Giang - Hoàng Anh</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Fashion/Views/Shared/_Login.cshtml
@model Fashion.Models.LoginViewModel
<div class="popup_wrap d_none" id="login_popup">
    <section class="popup r_corners shadow">
        <button class="bg_tr color_dark tr_all_hover text_cs_hover close f_size_large"><i class="fa fa-times"></i></button>
        <h3 class="m_bottom_20 color_dark">Đăng Nhập Hệ Thống</h3>
        @using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { role = "form" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <ul>
                <li class="m_bottom_15">
                    @Html.LabelFor(m => m.Email, new { @class = "m_bottom_5 d_inline_b" })<br>
                    @Html.TextBoxFor(m => m.Email, new { @class = "r_corners full_width" })
                    @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                </li>
                <li class="m_bottom_25">
                    @Html.LabelFor(m => m.Password, new { @class = "m_bottom_5 d_inline_b" })<br>
                    @Html.PasswordFor(m => m.Password, new { @class = "r_corners full_width" })
                    @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                </li>
              
                <li class="clearfix m_bottom_30">
                    <button class="button_type_4 tr_all_hover r_corners f_left bg_scheme_color color_light f_mxs_none m_mxs_bottom_15">Đăng Nhập</button>
                    <div class="f_right f_size_medium f_mxs_none">
                        @Html.ActionLink("Quên mật khẩu?", "ForgotPassword")
                    </div>
                </li>
            </ul>
        }
        <footer class="bg_light_color_1 t_mxs_align_c">
            <h3 class="color_dark d_inline_middle d_mxs_block m_mxs_bottom_15">@Html.ActionLink("Đăng Ký Thành Viên", "Register")</h3>
        </footer>
    </section>
</div>

Fashion/Views/Shared/_PopupView.cshtml
<div class="popup_wrap d_none" id="quick_view_product">
    <section class="popup r_corners shadow">
        <button class="bg_tr color_dark tr_all_hover text_cs_hover close f_size_large"><i class="fa fa-times"></i></button>
        <div class="clearfix">
            <div class="custom_scrollbar">
                <!--left popup column-->
                <div class="f_left half_column">
                    <div class="relative d_inline_b m_bottom_10 qv_preview">
                        <span class="hot_stripe"><img src="~/Content/images/sale_product.png" alt=""></span>
                        <img ng-show="vm.view.Images.length !== 0" src="../../{{vm.view.Images[0]}}" class="tr_all_hover" alt="">
                        <img ng-show="vm.view.Images.length === 0" src="~/Content/images/no.jpg" class="tr_all_hover" alt="">
                    </div>
                    <!--carousel-->
                    <div class="relative qv_carousel_wrap m_bottom_20">
                        <button class="button_type_11 t_align_c f_size_ex_large bg_cs_hover r_corners d_inline_middle bg_tr tr_all_hover qv_btn_prev">
                            <i class="fa fa-angle-left "></i>
                        </button>
                        <ul class="qv_carousel d_inline_middle">
                            <li ng-repeat="item in vm.view.Images" data-src="../../{{item}}"> <img src="../../{{item}}" alt=""></li>
                            <li data-src="~/Content/images/quick_view_img_1.jpg"><img src="~/Content/images/quick_view_img_4.jpg" alt=""></li>
                            <li data-src="~/Content/images/quick_view_img_2.jpg"><img src="~/Content/images/quick_view_img_5.jpg" alt=""></li>
                            <li data-src="~/Content/images/quick_view_img_3.jpg"><img src="~/Content/images/quick_view_img_6.jpg" alt=""></li>
                        </ul>
                        <button class="button_type_11 t_align_c f_size_ex_large bg_cs_hover r_corners d_inline_middle bg_tr tr_all_hover qv_btn_next">
                            <i class="fa fa-angle-right "></i>
                        </button>
                    </div>
                 
                </div>
                <!--right popup column-->
                <div class="f_right half_column">
                    <!--description-->
                    <h2 class="m_bottom_10"><a href="#" class="color_dark fw_medium">{{vm.view.Name}}</a></h2>
                    <div class="m_bottom_10">
                        <!--rating-->
                        <ul class="horizontal_list d_inline_middle type_2 clearfix rating_list tr_all_hover">
                            <li class="active">
                                <i class="fa fa-star-o empty tr_all_hover"></i>
                                <i class="fa fa-star active tr_all_hover"></i>
                            </li>
                            <li class="active">
                                <i class="fa fa-star-o empty tr_all_hover"></i>
                                <i class="fa fa-star active tr_all_hover"></i>
                            </li>
                            <li class="active">
                                <i class="fa fa-star-o empty tr_all_hover"></i>
                                <i class="fa fa-star active tr_all_hover"></i>
                            </li>
                            <li class="active">
                                <i class="fa fa-star-o empty tr_all_hover"></i>
                                <i class="fa fa-star active tr_all_hover"></i>
                            </li>
                            <li>
                                <i class="fa fa-star-o empty tr_all_hover"></i>
                                <i class="fa fa-star active tr_all_hover"></i>
                            </li>
                        </ul>
                        <a href="#" class="d_inline_middle default_t_color f_size_small m_left_5">1 Đánh Giá</a>
                    </div>
                    <hr class="m_bottom_10 divider_type_3">
                    <table class="description_table m_bottom_10">
                        <tr>
                            <td>Thương Hiệu: </td>
                            <td><a href="#" class="color_dark">{{vm.view.Brand}}</a></td>
                        </tr>
                        <tr>
                            <td>Danh Mục : </td>
                            <td><a href="#" class="color_dark">{{vm.view.Category}}</a></td>
                        </tr>
                        <tr>
                            <td>Tình trạng :</td>
                            <td><span class="color_green">Còn Hàng - </span> {{vm.view.InStock}} cái</td>
                        </tr>
                    </table>
                    <hr class="divider_type_3 m_bottom_10">
                    <p class="m_bottom_10">Thông tin thêm : {{vm.view.Info}}</p>
                    <hr class="divider_type_3 m_bottom_15">
                    <div class="m_bottom_15">
                        <span class="v_align_b f_size_ex_large">KHUYẾN MÃI : </span> <span class="v_align_b f_size_big m_left_5 scheme_color fw_medium">{{vm.view.Cost | number : c0}} VNĐ</span>
                    </div>
                    <table class="description_table type_2 m_bottom_15">
                        <tr>
                            <td class="v_align_m">Size:</td>
                            <td class="v_align_m">
                                <div class="custom_select f_size_medium relative d_inline_middle">
                                    <div class="select_title r_corners relative color_dark">S</div>
                                    <ul class="select_list d_none"></ul>

                                    <select ng-model="vm.size" name="product_name">
                                        <option ng-repeat="item in vm.view.Sizes" value="{{item}}">{{item}}</option>
                                        <option value="x">L</option>
                                        <option value="xs">XL</option>
                                    </select>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="v_align_m">Số Lượng :</td>
                            <td class="v_align_m">
                                <div class="clearfix quantity r_corners d_inline_middle f_size_medium color_dark">
                                    <button class="bg_tr d_block f_left" data-direction="down">-</button>
                                    <input type="text" name="" readonly ng-model="quantily" value="1" class="f_left">
                                    <button class="bg_tr d_block f_left" data-direction="up">+</button>
                                </div>
                            </td>
                        </tr>
                    </table>
                    <div class="clearfix m_bottom_15">
                        <button class="button_type_12 r_corners bg_scheme_color color_light tr_delay_hover f_left f_size_large">Thêm Vào Giỏ</button>
                        <button class="button_type_12 bg_light_color_2 tr_delay_hover f_left r_corners color_dark m_left_5 p_hr_0"><i class="fa fa-heart-o f_size_big"></i><span class="tooltip tr_all_hover r_corners color_dark f_size_small">Xem sau</span></button>
                        <button class="button_type_12 bg_light_color_2 tr_delay_hover f_left r_corners color_dark m_left_5 p_hr_0"><i class="fa fa-files-o f_size_big"></i><span class="tooltip tr_all_hover r_corners color_dark f_size_small">So Sánh</span></button>
                        <button class="button_type_12 bg_light_color_2 tr_delay_hover f_left r_corners color_dark m_left_5 p_hr_0 relative"><i class="fa fa-question-circle f_size_big"></i><span class="tooltip tr_all_hover r_corners color_dark f_size_small">Đặt câu hỏi</span></button>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>